/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.bgear.ui;

import com.bgear.dao.NhanVienDAO;
import com.bgear.entity.NhanVien;
import com.bgear.utils.MsgBox;
import java.util.List;

/**
 *
 * @author Admin
 */
public class DoiMatKhau extends javax.swing.JFrame {

    /**
     * Creates new form DangNhap
     */
    public DoiMatKhau() {
        initComponents();

    }

    NhanVienDAO nvdao = new NhanVienDAO();

    void ketThuc() {
        if (MsgBox.confirm(this, "Bạn có chắc muốn quay lại ?")) {
            new DangNhap().setVisible(true);
            dispose();
        }
    }

    boolean checkTaiKhoan() {
        List<NhanVien> list = nvdao.selectAll();
        for (NhanVien nv : list) {
            String maNV = nv.getMaNv();
            if (txtTenTaiKhoan.getText().equals(maNV)) {
                return true;//có tài khoản
            }
        }
        return false;//tài khoản không tồn tại
    }

    NhanVien getForm() {
        NhanVien nv = new NhanVien();
        nv.setMaNv(txtTenTaiKhoan.getText());
        nv.setMatKhau(txtNewPass.getText());
        return nv;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        btnXacNhan = new com.k33ptoo.components.KButton();
        kButton1 = new com.k33ptoo.components.KButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        txtOldPass = new javax.swing.JPasswordField();
        txtNewPass = new javax.swing.JPasswordField();
        txtReNewPass = new javax.swing.JPasswordField();
        jLabel7 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtTenTaiKhoan = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Đổi mật khẩu");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/bgear/icons/wepik-photo-mode-20221024-9529.png"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 470, 690));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnXacNhan.setText("Xác nhận");
        btnXacNhan.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        btnXacNhan.setkHoverEndColor(new java.awt.Color(204, 204, 204));
        btnXacNhan.setkHoverForeGround(new java.awt.Color(0, 0, 0));
        btnXacNhan.setkHoverStartColor(new java.awt.Color(204, 204, 204));
        btnXacNhan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXacNhanActionPerformed(evt);
            }
        });
        jPanel1.add(btnXacNhan, new org.netbeans.lib.awtextra.AbsoluteConstraints(96, 432, 120, 40));

        kButton1.setText("Quay lại");
        kButton1.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        kButton1.setkHoverEndColor(new java.awt.Color(204, 204, 204));
        kButton1.setkHoverForeGround(new java.awt.Color(0, 0, 0));
        kButton1.setkHoverStartColor(new java.awt.Color(204, 204, 204));
        kButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(kButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 432, 110, 40));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 0, 204));
        jLabel6.setText("Mật khẩu cũ");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(96, 216, -1, -1));

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(0, 0, 204));
        jLabel10.setText("Xác nhận mật khẩu mới");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(96, 360, -1, -1));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 51, 204));
        jLabel1.setText("ĐỔI MẬT KHẨU");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 60, 210, 40));

        txtOldPass.setBackground(new java.awt.Color(153, 204, 255));
        txtOldPass.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtOldPass.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(153, 204, 255)));
        jPanel1.add(txtOldPass, new org.netbeans.lib.awtextra.AbsoluteConstraints(96, 240, 320, 30));

        txtNewPass.setBackground(new java.awt.Color(153, 204, 255));
        txtNewPass.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtNewPass.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(153, 204, 255)));
        jPanel1.add(txtNewPass, new org.netbeans.lib.awtextra.AbsoluteConstraints(96, 312, 320, 30));

        txtReNewPass.setBackground(new java.awt.Color(153, 204, 255));
        txtReNewPass.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtReNewPass.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(153, 204, 255)));
        jPanel1.add(txtReNewPass, new org.netbeans.lib.awtextra.AbsoluteConstraints(96, 384, 320, 30));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 0, 204));
        jLabel7.setText("Mật khẩu mới");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(96, 288, -1, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 204));
        jLabel5.setText("Tên tài khoản");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(96, 144, 108, -1));

        txtTenTaiKhoan.setBackground(new java.awt.Color(153, 204, 255));
        txtTenTaiKhoan.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtTenTaiKhoan.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(153, 204, 255)));
        txtTenTaiKhoan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTenTaiKhoanActionPerformed(evt);
            }
        });
        jPanel1.add(txtTenTaiKhoan, new org.netbeans.lib.awtextra.AbsoluteConstraints(96, 168, 320, 30));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 0, 510, 690));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txtTenTaiKhoanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTenTaiKhoanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTenTaiKhoanActionPerformed

    private void btnXacNhanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXacNhanActionPerformed
        // TODO add your handling code here:
        if (txtTenTaiKhoan.getText().equals("") || txtOldPass.getText().equals("") || txtNewPass.getText().equals("") || txtReNewPass.getText().equals("")) {
            MsgBox.alert(this, "Không được để trống");
        } else {
            if (checkTaiKhoan() == false) { //tài khoản không tồn tại
                MsgBox.alert(this, "Tên tài khoản này không tồn tại");
                txtTenTaiKhoan.requestFocus();
            } else {
                List<NhanVien> list = nvdao.selectAll();
                boolean check = false;
                for (NhanVien nv : list) {
                    String matKhau = nv.getMatKhau();
                    if (txtOldPass.getText().equals(matKhau)) {
                        check = true;
                        break;
                    }
                }
                if (check == false) {
                    MsgBox.alert(this, "Mật khẩu cũ không chính xác");
                } else {
                    if (txtNewPass.getText().equals(txtReNewPass.getText())) {
                        NhanVien nv = getForm();
                        try {
                            nvdao.updatePassword(nv);
                            MsgBox.alert(this, "Đổi mật khẩu thành công");
                        } catch (Exception e) {
                            MsgBox.alert(this, "Đổi mật khẩu thất bại");
                        }
                    } else {
                        MsgBox.alert(this, "Bạn nhập sai mật khẩu xác nhận");
                    }
                }
            }
        }
    }//GEN-LAST:event_btnXacNhanActionPerformed

    private void kButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kButton1ActionPerformed
        // TODO add your handling code here:
        ketThuc();
    }//GEN-LAST:event_kButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DoiMatKhau.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DoiMatKhau.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DoiMatKhau.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DoiMatKhau.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Loading().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.k33ptoo.components.KButton btnXacNhan;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private com.k33ptoo.components.KButton kButton1;
    private javax.swing.JPasswordField txtNewPass;
    private javax.swing.JPasswordField txtOldPass;
    private javax.swing.JPasswordField txtReNewPass;
    private javax.swing.JTextField txtTenTaiKhoan;
    // End of variables declaration//GEN-END:variables
}
